 version: '2'
 services:
   db:
     image: postgres
   web:
     build: .
     command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db
     environment:
       - POSTGRES_NAME
       - POSTGRES_HOST
       - POSTGRES_PORT
       - POSTGRES_USER
       - POSTGRES_PASSWORD
       - DJANGO_PROD
       - DJANGO_SECRETKEY
