# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('prods', models.CharField(max_length=200)),
                ('nonterminals', models.CharField(max_length=4)),
                ('terminals', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnum', models.IntegerField()),
                ('category', models.CharField(choices=[('FI', 'first'), ('FO', 'follow'), ('LL', 'isLL1')], max_length=2)),
                ('symbol', models.CharField(blank=True, max_length=1)),
                ('answer', models.CharField(max_length=4)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LL1_Academy.Grammar')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('gid', 'qnum')]),
        ),
    ]
