# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LL1_Academy', '0003_auto_20170510_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='prods',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('FI', 'first'), ('FO', 'follow'), ('LL', 'isLL1'), ('PT', 'parseTable')], max_length=2),
        ),
    ]
