# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LL1_Academy', '0004_auto_20170511_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='prods',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=200),
        ),
    ]
