# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 07:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LL1_Academy', '0006_auto_20170511_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='grammar',
            name='nComplete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grammar',
            name='nSkip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grammar',
            name='nStart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='nCorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='nGiveUp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='nWrong',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='grammar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LL1_Academy.Grammar'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userhistory',
            unique_together=set([('user', 'grammar')]),
        ),
    ]
