# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LL1_Academy', '0007_auto_20170516_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
