# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LL1_Academy', '0008_auto_20170518_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='updateTime',
            field=models.DateTimeField(),
        ),
    ]
