# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LL1_Academy', '0009_auto_20170518_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
