 version: "3"
 services:
   seleniumserver:
     image: selenium/standalone-chrome:3.4.0
     ports:
       - "4444:4444"
   seleniumclient:
     build:
       context: .
       dockerfile: Dockerfile.testing
     command: python testing.py testing_seleniumserver_1 https://sheltered-sands-11346.herokuapp.com
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - seleniumserver
